package com.brcode.app;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import java.util.*;

public class MainActivity extends Activity {
  LinearLayout root, content, messages; SharedPreferences prefs;
  final int G=Color.rgb(0,255,115), BG=Color.rgb(3,6,5), PANEL=Color.rgb(9,15,13), PANEL2=Color.rgb(12,21,18), BORDER=Color.rgb(22,70,49), W=Color.WHITE, M=Color.rgb(145,160,153), RED=Color.rgb(255,70,90);
  int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
  TextView text(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);return t;}
  GradientDrawable bg(int c,int stroke,int r){GradientDrawable d=new GradientDrawable();d.setColor(c);d.setCornerRadius(dp(r));if(stroke>0)d.setStroke(dp(1),stroke);return d;}
  LinearLayout.LayoutParams lp(int w,int h){return new LinearLayout.LayoutParams(w,h);}
  LinearLayout.LayoutParams m(int w,int h,int top,int bottom){LinearLayout.LayoutParams p=lp(w,h);p.setMargins(0,dp(top),0,dp(bottom));return p;}
  Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextSize(14);b.setTextColor(W);b.setAllCaps(false);b.setPadding(dp(10),0,dp(10),0);b.setBackground(bg(PANEL2,BORDER,12));return b;}
  @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.BLACK);getWindow().setNavigationBarColor(Color.BLACK);prefs=getSharedPreferences("brcode",0);if(!prefs.contains("u"))prefs.edit().putString("u","Caua_").putString("p","123456").apply();showHome(prefs.getString("u","Caua_"));}
  void base(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);root.setPadding(dp(12),dp(8),dp(12),dp(5));setContentView(root);}
  void top(String title,String sub,View.OnClickListener back){LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);if(back!=null){Button b=btn("‹");b.setTextSize(30);b.setOnClickListener(back);bar.addView(b,lp(dp(48),dp(48)));}LinearLayout tt=new LinearLayout(this);tt.setOrientation(LinearLayout.VERTICAL);TextView a=text(title,20,W);a.setTypeface(Typeface.DEFAULT,Typeface.BOLD);tt.addView(a);if(sub!=null)tt.addView(text(sub,11,M));bar.addView(tt,lp(0,dp(50)));((LinearLayout.LayoutParams)tt.getLayoutParams()).weight=1;root.addView(bar);}
  void bottom(String u,String active){LinearLayout n=new LinearLayout(this);n.setGravity(Gravity.CENTER);n.setPadding(0,dp(3),0,0);String[][] x={{"⌂","Início","home"},{"💬","Chat","chat"},{"👥","Comunidades","comm"},{"👤","Perfil","profile"}};for(String[] a:x){Button b=btn(a[0]+"\n"+a[1]);b.setTextSize(10);b.setGravity(Gravity.CENTER);b.setBackgroundColor(Color.TRANSPARENT);b.setTextColor(a[2].equals(active)?G:M);String k=a[2];b.setOnClickListener(v->{if(k.equals("home"))showHome(u);else if(k.equals("chat"))showChat(u);else if(k.equals("comm"))showCommunity(u);else showProfile(u);});n.addView(b,lp(0,dp(58)));((LinearLayout.LayoutParams)b.getLayoutParams()).weight=1;}root.addView(n,lp(-1,dp(61)));}
  TextView section(String s){TextView t=text(s.toUpperCase(),11,M);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);content.addView(t,m(-1,dp(24),12,4));return t;}
  void scrollContent(){ScrollView sv=new ScrollView(this);sv.setFillViewport(true);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);sv.addView(content);root.addView(sv,lp(-1,0));((LinearLayout.LayoutParams)sv.getLayoutParams()).weight=1;}
  void showAuth(){base();root.setGravity(Gravity.CENTER);TextView logo=text("⚡ BRcode",38,G);logo.setGravity(Gravity.CENTER);root.addView(logo,lp(-1,dp(60)));TextView s=text("Conecte • Converse • Crie",15,M);s.setGravity(Gravity.CENTER);root.addView(s,lp(-1,dp(35)));LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(18),dp(18),dp(18),dp(18));card.setBackground(bg(PANEL, BORDER,18));root.addView(card,m(-1,-2,18,0));EditText u=field("Usuário","Caua_");EditText p=field("Senha","123456");p.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);card.addView(u,lp(-1,dp(52)));card.addView(p,m(-1,dp(52),10,0));Button in=btn("ENTRAR");in.setTextColor(Color.BLACK);in.setTypeface(Typeface.DEFAULT,Typeface.BOLD);in.setBackground(bg(G,0,12));in.setOnClickListener(v->{String a=u.getText().toString().trim(),q=p.getText().toString();if((a.equals("Caua_")&&q.equals("123456"))||(a.equals(prefs.getString("u",""))&&q.equals(prefs.getString("p",""))))showHome(a);else toast("Usuário ou senha inválidos");});card.addView(in,m(-1,dp(52),14,0));Button cr=btn("Criar conta");cr.setOnClickListener(v->{String a=u.getText().toString().trim(),q=p.getText().toString();if(a.length()<3||q.length()<4){toast("Preencha usuário e senha");return;}prefs.edit().putString("u",a).putString("p",q).apply();showHome(a);});card.addView(cr,m(-1,dp(50),8,0));}
  EditText field(String hint,String value){EditText e=new EditText(this);e.setHint(hint);e.setText(value);e.setSingleLine();e.setTextColor(W);e.setHintTextColor(M);e.setBackground(bg(Color.rgb(6,11,9),BORDER,12));e.setPadding(dp(12),0,dp(12),0);return e;}
  void showHome(String u){base();top("⚡ BRcode","● Online",v->showProfile(u));ScrollView sv=new ScrollView(this);LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(2),dp(8),dp(2),dp(8));sv.addView(c);root.addView(sv,lp(-1,0));((LinearLayout.LayoutParams)sv.getLayoutParams()).weight=1;
    LinearLayout profile=new LinearLayout(this);profile.setGravity(Gravity.CENTER_VERTICAL);profile.setPadding(dp(12),dp(8),dp(12),dp(8));profile.setBackground(bg(PANEL,BORDER,16));TextView avatar=text("C",22,Color.BLACK);avatar.setGravity(Gravity.CENTER);avatar.setBackground(bg(G,0,50));profile.addView(avatar,lp(dp(48),dp(48)));LinearLayout who=new LinearLayout(this);who.setOrientation(LinearLayout.VERTICAL);TextView name=text(u,17,W);name.setTypeface(Typeface.DEFAULT,Typeface.BOLD);who.addView(name);who.addView(text("👑 Proprietário • online",12,G));profile.addView(who,m(0,dp(50),0,0));((LinearLayout.LayoutParams)who.getLayoutParams()).weight=1;Button bell=btn("🔔");bell.setOnClickListener(v->notifications(u));profile.addView(bell,lp(dp(48),dp(48)));c.addView(profile,m(-1,dp(66),4,8));
    TextView search=text("🔎  Pesquisar no BRcode...",14,M);search.setGravity(Gravity.CENTER_VERTICAL);search.setPadding(dp(14),0,0,0);search.setBackground(bg(PANEL2,BORDER,14));search.setOnClickListener(v->toast("Pesquisa: em breve conectada ao servidor"));c.addView(search,lp(-1,dp(50)));
    TextView st=text("SUAS COMUNIDADES",11,M);st.setTypeface(Typeface.DEFAULT,Typeface.BOLD);c.addView(st,m(-1,dp(25),14,3));communityCard(c,"🟢","BRcode Brasil","8 canais • 24 online",v->showCommunity(u));communityCard(c,"🎮","Gaming Brasil","5 canais • 12 online",v->showCommunity(u));
    st=text("ACESSO RÁPIDO",11,M);st.setTypeface(Typeface.DEFAULT,Typeface.BOLD);c.addView(st,m(-1,dp(25),14,3));quick(c,"💬","Chat","Converse com a comunidade",v->showChat(u));quick(c,"🎙️","Voz","Salas de voz e chamadas",v->showVoice(u));quick(c,"📹","Vídeo","Chamadas de vídeo",v->showVideo(u));quick(c,"👫","Amigos","Mensagens privadas",v->showFriends(u));quick(c,"🤖","Bots","Bots e automações",v->showBots(u));quick(c,"🛡️","Moderação","Painel do proprietário",v->showModeration(u));bottom(u,"home");}
  void communityCard(LinearLayout c,String ic,String title,String desc,View.OnClickListener click){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(dp(10),dp(7),dp(10),dp(7));r.setBackground(bg(PANEL,BORDER,14));TextView i=text(ic,24,W);r.addView(i,lp(dp(48),dp(54)));LinearLayout t=new LinearLayout(this);t.setOrientation(LinearLayout.VERTICAL);TextView a=text(title,16,W);a.setTypeface(Typeface.DEFAULT,Typeface.BOLD);t.addView(a);t.addView(text(desc,11,M));r.addView(t,lp(0,dp(54)));((LinearLayout.LayoutParams)t.getLayoutParams()).weight=1;TextView ar=text("›",28,G);r.addView(ar,lp(dp(30),dp(54)));r.setOnClickListener(click);c.addView(r,m(-1,dp(64),4,0));}
  void quick(LinearLayout c,String ic,String title,String desc,View.OnClickListener click){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(dp(12),0,dp(8),0);r.setBackground(bg(PANEL2,BORDER,12));TextView i=text(ic,23,W);r.addView(i,lp(dp(45),dp(55)));LinearLayout t=new LinearLayout(this);t.setOrientation(LinearLayout.VERTICAL);t.addView(text(title,15,W));t.addView(text(desc,11,M));r.addView(t,lp(0,dp(55)));((LinearLayout.LayoutParams)t.getLayoutParams()).weight=1;TextView ar=text("›",26,G);r.addView(ar,lp(dp(28),dp(55)));r.setOnClickListener(click);c.addView(r,m(-1,dp(59),4,0));}
  void showCommunity(String u){base();top("BRcode Brasil","Comunidade • 24 online",v->showHome(u));LinearLayout server=new LinearLayout(this);server.setPadding(0,dp(5),0,dp(5));String[] sv={"🟢","🎮","🎵","➕"};for(String x:sv){Button b=btn(x);b.setTextSize(20);b.setBackground(bg(x.equals("🟢")?G:PANEL2,BORDER,50));b.setTextColor(x.equals("🟢")?Color.BLACK:W);server.addView(b,m(dp(52),dp(52),0,0));}root.addView(server,lp(-1,dp(62)));content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);ScrollView sc=new ScrollView(this);sc.addView(content);root.addView(sc,lp(-1,0));((LinearLayout.LayoutParams)sc.getLayoutParams()).weight=1;
    section("Canais de texto");channel("#  geral","Conversa principal",true,u);channel("#  anúncios","Novidades do BRcode",false,u);channel("#  memes","Diversão da comunidade",false,u);channel("#  suporte","Ajuda e suporte",false,u);section("Canais de voz");channel("🎙️  Geral","3 pessoas online",false,u);channel("🎮  Gaming","5 pessoas online",false,u);section("Online agora");member("🟢","Caua_","Proprietário",G);member("🟢","BRcode Bot","Bot",G);member("🟢","Visitante","Membro",W);bottom(u,"comm");}
  void channel(String name,String desc,boolean active,String u){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(dp(12),0,dp(8),0);r.setBackground(bg(active?Color.rgb(15,35,25):Color.TRANSPARENT,active?BORDER:0,10));TextView a=text(name,16,active?W:M);a.setTypeface(Typeface.DEFAULT,Typeface.BOLD);r.addView(a,lp(0,dp(54)));((LinearLayout.LayoutParams)a.getLayoutParams()).weight=1;r.addView(text("›",22,active?G:M),lp(dp(25),dp(54)));r.setOnClickListener(v->{if(name.contains("Geral")&&name.contains("🎙️"))showVoice(u);else showChat(u);});content.addView(r,m(-1,dp(55),2,0));}
  void member(String ic,String n,String role,int color){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(dp(8),0,0,0);r.addView(text(ic,12,color),lp(dp(24),dp(48)));LinearLayout t=new LinearLayout(this);t.setOrientation(LinearLayout.VERTICAL);t.addView(text(n,14,W));t.addView(text(role,10,M));r.addView(t);content.addView(r,lp(-1,dp(48)));}
  void showChat(String u){base();top("# geral","BRcode Brasil • texto",v->showHome(u));content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);ScrollView sc=new ScrollView(this);messages=new LinearLayout(this);messages.setOrientation(LinearLayout.VERTICAL);sc.addView(messages);content.addView(sc,lp(-1,0));((LinearLayout.LayoutParams)sc.getLayoutParams()).weight=1;root.addView(content,lp(-1,0));((LinearLayout.LayoutParams)content.getLayoutParams()).weight=1;msg("BRcode Bot","Bem-vindo ao # geral! 👋",G);msg("Caua_","Este é o meu espaço no BRcode.",G);msg("Visitante","Olá! 👋",W);LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);EditText e=field("Mensagem em # geral","");bar.addView(e,lp(0,dp(52)));((LinearLayout.LayoutParams)e.getLayoutParams()).weight=1;Button plus=btn("＋");bar.addView(plus,lp(dp(50),dp(52)));Button send=btn("➤");send.setBackground(bg(G,0,12));send.setTextColor(Color.BLACK);send.setOnClickListener(v->{String q=e.getText().toString().trim();if(!q.isEmpty()){msg(u,q,W);e.setText("");sc.post(()->sc.fullScroll(View.FOCUS_DOWN));}});bar.addView(send,lp(dp(52),dp(52)));root.addView(bar,m(-1,dp(58),4,0));bottom(u,"chat");}
  void msg(String who,String s,int color){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(10),dp(7),dp(10),dp(7));TextView a=text(who,13,color);a.setTypeface(Typeface.DEFAULT,Typeface.BOLD);r.addView(a);r.addView(text(s,14,M));messages.addView(r,m(-1,-2,2,2));}
  void page(String title,String sub,String active,String[] items,String u){base();top(title,sub,v->showHome(u));scrollContent();for(String x:items){Button b=btn(x);b.setGravity(Gravity.CENTER_VERTICAL);b.setTextSize(15);b.setOnClickListener(v->toast(x+" aberto"));content.addView(b,m(-1,dp(58),5,0));}bottom(u,active);}
  void showVoice(String u){page("Voz","Salas de voz • conecte-se", "home",new String[]{"🎙️  Geral                 • 3 online","🎮  Gaming               • 5 online","🎵  Música               • 2 online","➕  Criar sala de voz"},u);}
  void showVideo(String u){page("Vídeo","Chamadas de vídeo", "home",new String[]{"📹  Iniciar chamada","👥  Chamada em grupo","🎥  Compartilhar tela"},u);}
  void showFriends(String u){page("Amigos","Privado • mensagens e solicitações","home",new String[]{"🟢  Caua_ • online","➕  Adicionar amigo","📨  Solicitações","💬  Mensagens privadas"},u);}
  void showBots(String u){page("Bots","Automação da comunidade","home",new String[]{"🤖  BRcode Bot • online","🎵  Music Bot • online","⚙️  Comandos","➕  Adicionar bot"},u);}
  void showModeration(String u){page("Moderação","Painel do proprietário 👑","home",new String[]{"🛡️  Permissões e cargos","🔨  Banimentos","🔇  Silenciados","📋  Registro de ações","⚙️  Configuração da comunidade"},u);}
  void notifications(String u){page("Notificações","Tudo que aconteceu no BRcode","home",new String[]{"💬  3 novas mensagens","👥  Nova solicitação de amizade","🛡️  Nenhum alerta de moderação"},u);}
  void showProfile(String u){base();top("Perfil","Sua conta BRcode",v->showHome(u));scrollContent();LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setGravity(Gravity.CENTER);card.setPadding(dp(12),dp(18),dp(12),dp(18));card.setBackground(bg(PANEL,BORDER,16));TextView av=text("C",34,Color.BLACK);av.setGravity(Gravity.CENTER);av.setBackground(bg(G,0,60));card.addView(av,lp(dp(74),dp(74)));TextView n=text(u,23,W);n.setTypeface(Typeface.DEFAULT,Typeface.BOLD);n.setGravity(Gravity.CENTER);card.addView(n,m(-1,dp(34),8,0));TextView role=text("👑 Proprietário do BRcode  •  🟢 online",12,G);role.setGravity(Gravity.CENTER);card.addView(role,lp(-1,dp(25)));content.addView(card,lp(-1,-2));String[] xs={"⚙️  Configurações","🔔  Notificações","🛡️  Painel de moderação","🔒  Privacidade e segurança","ℹ️  Sobre o BRcode"};for(String x:xs){Button b=btn(x);b.setGravity(Gravity.CENTER_VERTICAL);b.setOnClickListener(v->{if(x.contains("moderação"))showModeration(u);else if(x.contains("Notificações"))notifications(u);else toast(x+" aberto");});content.addView(b,m(-1,dp(56),7,0));}Button out=btn("Sair da conta");out.setTextColor(RED);out.setOnClickListener(v->showAuth());content.addView(out,m(-1,dp(56),18,0));bottom(u,"profile");}
  void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
}
